name: Deploy to NuxtHub (app 1)
on: push

jobs:
  deploy:
    name: "Deploy to NuxtHub"
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/master' && 'production' || 'preview' }}
      url: ${{ steps.deploy.outputs.deployment-url }}
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: app-1

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Ensure NuxtHub module is installed
        run: npx nuxthub@latest ensure

      - name: Build application
        run: pnpm build

      - name: Deploy to NuxtHub
        uses: nuxt-hub/action@feat/improve-error-logs
        id: deploy
        with:
          project-key: monorepo-branch-oxuf
          directory: app-1/dist
          hub-url: https://fix-cicd-token-logging.nuxthub.pages.dev
